### ISSUE TITLE
Authorisation fails.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [dom96/chirper.picheta.me#2]
When I authorize the extension with the popup window, the extension still states ["Needs login..."](https://user-images.githubusercontent.com/42837531/216731542-e826a3cf-b924-494c-a168-a4660a83a62b.png) when I invoke it again.

If I manually enable [its (silently) optionally requested permissions via about:addons](https://user-images.githubusercontent.com/42837531/216731661-c8147425-f6da-4280-acdb-fe8826a6a89b.png), ![this](https://user-images.githubusercontent.com/42837531/216731741-9018c812-dc2c-4651-8942-7b16a89ba8d4.png) appears after reauthenticating. Additionally, it remains unauthenticated.

My username is `@rokejulianlockhart@mastodon.social`.

**Comment by beedell-roke** [comment]
I just tried inputting `rokejulianlockhart@mastodon.social` instead of `@rokejulianlockhart@mastodon.social`. I don't know which of the aforestated actually remediated the problem, but it at least works now!

**Comment by dom96** [comment]
Thanks for reporting!

Hmm, I don't see any Chirper-specific errors in the console screenshot you've shared. I'll see if I can repro with the `@` missing (I include it at the start when testing).

**Comment by dom96** [comment]
Just tested this and cannot reproduce any issues.
